variables:
  UserInput: "url.txt"


stages:
    - reading_URL
    - upload

Reading-URL:
    stage: reading_URL
    before_script:
        - mkdir -p target/arun
        - ls -l
      
        
    script:
        - | 
          if [ -f "$UserInput" ]; then
            while IFS='' read -r line || [[ -n "$line" ]]; do
                echo "$line"
                cd target/arun && { curl -O $line ; cd -; }
                ls -l target/arun
          
                pwd
                ls -l /home/gitlab-runner/builds/zvN6MqxH/0/ecs_automation/url/target/arun

                done < "$UserInput"
          else
            echo "File not found: $UserInput"
          fi
    artifacts:
      paths:
        - target/arun
        - target/*

      
file-creation:
    image: linux
    stage: upload
    before_script:
        - ls
    script:
        #- apt update -y
        #- apt install sshpass
        - cd target/arun
        - ls
        - |
          sshpass -p "pass" sftp -o StrictHostKeyChecking=accept-new  -oPort=2222 foo@52.0.107.73 << !
          cd upload
          put *.xlsx
          bye
          !
        - ls

       
      
        


        

      
    
       
        




